apiVersion: v1
kind: ConfigMap
metadata:
  namespace: anotherclass-212
  name: {{ include "api-tester.fullname" . }}-properties
  labels:
    {{- include "api-tester.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data.properties | nindent 2 }}
